import { build } from "esbuild";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

// Build the self-contained preview into dist/ (committed so index.html opens
// with no build step). CSS is generated by the Tailwind CLI; JS is bundled by
// esbuild with React + Framer Motion inlined.
const dir = path.dirname(fileURLToPath(import.meta.url));
process.chdir(dir);

console.log("• tailwind → dist/styles.css");
execSync(
  "node_modules/.bin/tailwindcss -i src/styles.css -o dist/styles.css --minify",
  { stdio: "inherit" },
);

console.log("• esbuild → dist/bundle.js");
await build({
  entryPoints: ["src/main.tsx"],
  bundle: true,
  outfile: "dist/bundle.js",
  format: "iife",
  minify: true,
  sourcemap: false,
  jsx: "automatic",
  target: ["es2019"],
  define: { "process.env.NODE_ENV": '"production"' },
  logLevel: "info",
});

console.log("✓ build complete");
